name: "[Analysis] Run a TFLint scan against Terraform code"
description: "Run TFLint to lint Terraform code"
inputs:
  scan_directory:
    description: "The directory to run the TFLint scan in"
    default: "."
    required: false
  download_tflint:
    description: "Whether to download and install TFLint if it's not already available"
    default: true
    required: false

runs:
  using: "composite"
  steps:
    - name: Verify TFLint Installation
      id: install_check
      shell: bash
      run: |
        if command -v tflint >/dev/null 2>&1; then
          echo "TFLint is installed."
        else
          echo "TFLint is not installed in the terraform-ci container."
          exit 1
        fi

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Verify .tflint.hcl Presence
      id: tflint_hcl_check
      shell: bash
      run: |
        if [ -f ".tflint.hcl" ]; then
          echo ".tflint.hcl file is present."
        else
          echo ".tflint.hcl not found in the terraform-ci container."
          exit 1
        fi

    - name: Initialize TFLint
      shell: bash
      run: tflint init

    - name: Execute TFLint Scan
      shell: bash
      env:
        SCAN_DIRECTORY: ${{ inputs.scan_directory }}
      run: |
        tflint --recursive "$SCAN_DIRECTORY"

