name: "[Analysis] Run a Checkov scan against Terraform code"
description: "Run a light or deep Checkov scan"
inputs:
  scan_type:
    description: "The type of scan to run against Terraform. Either 'deep' or 'light'. Deep requires a Terraform plan file"
    default: light
    required: false
  tfplan_file:
    description: "The filename of the Terraform plan. Required if using 'deep' scan_type."
    default: "tfplan"
    required: false
  upload_sarif:
    description: "Upload resulting Sarif file to the Github Security tab"
    default: true
    required: false
  scan_directory:
    description: "The directory to run the scan in or to use as the REPO_ROOT_FOR_PLAN_ENRICHMENT"
    default: "."
    required: false

runs:
  using: "composite"
  steps:
    - name: Check if dependencies are already installed
      id: install_check
      shell: bash
      run: |
        if [[ $(which checkov) ]]; then
          echo "checkov_installed=True" >> $GITHUB_OUTPUT
        else
          echo "checkov_installed=False" >> $GITHUB_OUTPUT
        fi
        if [[ $(which python) && $(which pip) ]]; then
          echo "python_installed=True" >> $GITHUB_OUTPUT
        else
          echo "python_installed=False" >> $GITHUB_OUTPUT
        fi

    - uses: actions/setup-python@v5
      if: ${{ steps.install_check.outputs.python_installed == 'False' && steps.install_check.outputs.installed == 'False' }}
      with:
        python-version: "3.12"

    - name: Install requirements.txt
      if: ${{ steps.install_check.outputs.checkov_installed == 'False' }}
      shell: bash
      run: pip install -r ${{ github.action_path }}/requirements.txt

    - name: Run Checkov
      shell: bash
      env:
        SCAN_TYPE: ${{ inputs.scan_type }}
        TFPLAN_FILE: ${{ inputs.tfplan_file }}
        DIRECTORY: ${{ inputs.scan_directory }}
      run: |
        if [[ "$SCAN_TYPE" == 'deep' ]]; then
          checkov --framework terraform_plan --download-external-modules true --deep-analysis --output cli --output sarif --output-file-path console,results.sarif --repo-root-for-plan-enrichment "$DIRECTORY" --file "$TFPLAN_FILE"
        else
          checkov --framework terraform --hard-fail-on HIGH --output cli --output sarif --output-file-path console,results.sarif --directory "$DIRECTORY"
        fi

      # This would normally use github/codeql-action/upload-sarif@v2
      # Is always skipped as we don't currently enable Advanced Security.
    - name: Upload Checkov results to Security Tab
      env:
        GH_TOKEN: ${{ github.token }}
      if: ${{ false && inputs.upload_sarif == true }}
      shell: bash
      run: |
        sarif_content=$(gzip -c results.sarif | base64 -w0)
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${GITHUB_REPOSITORY}/code-scanning/sarifs \
          -f "commit_sha=${GITHUB_SHA}" \
          -f "ref=${GITHUB_REF}" \
          -f "sarif=${sarif_content}"
