name: 'Create dependency graph'
description: 'Graphs dependency order of Terraform stacks using dependencies.json and returns sorted order in JSON format'
inputs:
  reverse:
    description: "Reverse the list of stacks. Can be required if running a terraform destroy"
    required: false
    default: false
outputs:
  json_directory_list:
    description: "List of the stacks to deploy in dependency order in JSON format"
    value: ${{ steps.stack_order.outputs.order }}

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install requirements.txt
      shell: bash
      run: pip install -r ${{ github.action_path }}/requirements.txt

    - name: Find order of stacks
      shell: bash
      id: stack_order
      run: |
        [[ ${{ inputs.reverse}} == 'false' ]] || reverse_flag="--reverse" 
        echo "order=$(python ${{ github.action_path }}/main.py $reverse_flag)" >> $GITHUB_OUTPUT
        