name: "[Analysis] Run a Prowler scan against a cloud provider"
description: "Run a light or deep Checkov scan"
inputs:
  cloud_provider:
    description: "The cloud provider to run against. Either 'aws' or 'azure'"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Prowler
      shell: bash
      run: pip install prowler

    - name: Prowl AWS with Prowler
      shell: bash
      env:
        PROVIDER: ${{ inputs.cloud_provider }}
      run: |
        if [[ "$PROVIDER" == "aws" ]] || [[ "$PROVIDER" == "azure" ]]; then
          prowler "$PROVIDER" --output-modes csv --compliance "cis_2.0_$PROVIDER" --ignore-exit-code-3
        else
          echo "$PROVIDER not supported"
        fi

    - name: Upload CSV artifacts
      uses: actions/upload-artifact@v4
      with:
        name: prowler-csv
        path: ./output/compliance/
